blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/ft8FYjcdnb
    about: You can talk to people about your thing here.
  - name: GitHub Discussions Q&A
    url: https://github.com/Elektron-blip/miniature-engine/discussions/categories/q-a
    about: Have more questions? Ask the community over here.
  - name: GitHub Discussions General
    url: https://github.com/Elektron-blip/miniature-engine/discussions
    about: Check to see if someone else already has the same ideas/problems.
