name: TypeScript Build

on: [push, workflow_dispatch]

permissions: write-all

jobs:
  compile:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
    - name: Install packages
      run: npm i
    - name: Build and push
      uses: alexthemaster/action-build-typescript@v1.2.1 
      with:
        pushToBranch: true 
        branch: 'main-javascript'
        githubToken: ${{ secrets.GITHUB_TOKEN }} 
      
