name: TypeScript Build

on: [push, workflow_dispatch]

permissions: read-all|write-all

jobs:
  compile:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: true
        fetch-depth: 0
    - name: TypeScript Build
      uses: alexthemaster/action-build-typescript@v1.2.1
      with:
        pushToBranch: "${{ github.ref }}-javascript"
        branch: ${{ github.ref }}
      
