name: TypeScript Build

on: [push, workflow_dispatch]

permissions: write-all

jobs:
  compile:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 16
    - name: Install packages
      run: |
        npm i -D typescript
        npm i -D @types/node
        npm i
    - name: TypeScript Build
      uses: alexthemaster/action-build-typescript@v1.2.1
      with:
        pushToBranch: true
        branch: main-javascript
        githubToken: ${{ github.token }}
        # The name of the branch the action should push the compiled code
        branch: # optional, default is dist
        # Your GitHub secret token
        githubToken: # optional
        
      
